version: '3.9'
services:
  database:
    image: postgres:15
    restart: ${RESTART_POLICY}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=${TZ}
    ports:
      - '5433:5432'
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data:cached
    networks:
      - medusa
networks:
  medusa:
    name: medusa
